language: android
jdk: oraclejdk7

env:
    global:
        - DEPLOYGATE_USER=takahirom
        - secure: "R6swwzhT1KOTL9w063/t/klGpmO1eJC1w35M0Dzejuvl4FoD9ZioQAUMsLXDPoaXGmK6vF0UZifHujs/2fQ3EJC71vtn9ZLPNP8V9zOzkm7k4UJ4x7S9iKutrCbRCimssirGeENnZO3x6vyoe/NId8gZ8Ti04i4g5f082JTjmEI="

android:
    components:
        - build-tools-21.0.2
        
script: bash gradlew uploadDeployGateDebug  --info --debug 
