language: android
jdk: oraclejdk7

env:
    global:
        - DEPLOYGATE_USER=takahirom
        - secure: "fmKoI6l0FWMEH/5y003hCfhcwGVwwyfePZAUrZZgY7T1Ah5V+cl5TnKSmJwY/fNyA8y+QWJYsc/rRqViBrVsktIo7j0qIrYO20RFYyxcyWSMyUrbywSr1cNM0MJztYaX8JxaBj7H0KJ5h6Ti6IUtZ25hh4BH9JUyTwpt83hEzJM="

android:
    components:
        - build-tools-21.0.2
        
script: bash gradlew uploadDeployGateDebug
